# .travis.yml

language: node_js
node_js:
  - 13

services:
  - docker


# Pre-testing installs
install:
  - echo "nothing needs to be installed"

  
# Pre-testing installs
install:
  - echo "nothing needs to be installed"


script:
  # Xây dựng hình ảnh Docker
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed thanvv2/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user thanvv2/udagram-api-user:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend thanvv2/udagram-frontend:v1
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy thanvv2/udagram-reverseproxy:v1 

  after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


  # Đẩy hình ảnh lên DockerHub
  - docker push thanvv2/udagram-api-feed:v1
  - docker push thanvv2/udagram-api-user:v1
  - docker push thanvv2/udagram-frontend:v1
  - docker push thanvv2/udagram-reverseproxy:v1